# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ecd8027926965a745818f30bb7f90b4789fcc2e6f3c8d4a742606f49cc35fc9ca39415f42b0ffc60ad794aea5c8dcd7bb6b8280d9fe4ff8abf8b2d949239521f

test:
  secret_key_base: 4cff3d4b2ce71ab17a08804586e591704f24aa3341ec57dd78bb98c007fdffeef726b1f9f026cb361ced2ddf414e4d2e5eb74002c8bb4ce9d80396761b4aff85

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
