# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2c15f45501d49c42d37289a94c6d9c52f7305b7fd4249938ad8319b6163b77ca3122b1a2a3f7a1fe031d25a47ad100c1c4418957b7a5c9745f7aa7d930492057

test:
  secret_key_base: 0633638395b62b7975f7ebfdad6bf04f25ea9db206d13b8b308891d2c35491d4fefb38707f6afae231cedfbd177f32d9dfe7425ef66091f7eae00964d3755339

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
